let state, view='top', selectedAssetId=null, drawWall=false, wallStart=null, selectedCategory='配电箱';
const key='facility_mvp_latest_v1';
function demo(){return {areas:[{id:'a1',name:'民企区',buildings:[{id:'b5',name:'5栋',x:120,y:80,rot:0,floors:[{id:'f51',name:'1F',height:3.6,length:48,width:32,planImage:'',walls:[{x1:90,y1:80,x2:720,y2:80},{x1:720,y1:80,x2:720,y2:410},{x1:720,y1:410,x2:90,y2:410},{x1:90,y1:410,x2:90,y2:80},{x1:300,y1:80,x2:300,y2:410},{x1:90,y1:230,x2:720,y2:230}],assets:[{id:'e1',type:'配电箱',name:'1F配电箱A01',x:180,y:150,info:{code:'DB-5-1F-001',area:'民企区',building:'5栋',floor:'1F',location:'配电室东侧',responsible:'张三',incomingCable:'YJV-4X95+1X50',incomingSource:'上级配电箱 DB-5-1F-0001',mainSwitch:'MCCB-250A/3P',voltage:'380V',ratedCurrent:'250A',outgoing:[['QF1','160A/3P','空调机组'],['QF2','63A/3P','照明'],['QF3','32A/3P','插座']] }},{id:'e2',type:'空调机组',name:'空调机组-1',x:520,y:170,info:{型号:'MDV-250W',保养内容:'清洗滤网、检查冷媒、检查电机',保养周期:'3个月',下次保养:'2024-08-01'}}]},{id:'f52',name:'2F',height:3.6,length:48,width:32,planImage:'',walls:[],assets:[]}]}]}],categories:{'配电箱':['设备编号','安装日期','负责人','备注'],'空调机组':['型号','品牌','功率(kW)','保养内容','保养周期','下次保养'],'水泵':['型号','流量','扬程','功率(kW)','保养内容','保养时间']}}}
function $(id){return document.getElementById(id)}
function login(){if($('username').value==='admin'&&$('password').value==='admin123'){$('login').classList.add('hidden');$('app').classList.remove('hidden');init()}else alert('账号或密码错误')}
function init(){state=JSON.parse(localStorage.getItem(key)||'null')||demo();bindSelectors();renderAll()}
function saveData(){localStorage.setItem(key,JSON.stringify(state));alert('已保存')}
function resetDemo(){if(confirm('恢复示例会覆盖当前浏览器数据')){state=demo();saveData();bindSelectors();renderAll()}}
function currentArea(){return state.areas.find(a=>a.id==$('areaSelect').value)||state.areas[0]}
function currentBuilding(){return currentArea().buildings.find(b=>b.id==$('buildingSelect').value)||currentArea().buildings[0]}
function currentFloor(){return currentBuilding().floors.find(f=>f.id==$('floorSelect').value)||currentBuilding().floors[0]}
function bindSelectors(){let a=$('areaSelect');a.innerHTML=state.areas.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');a.onchange=()=>{bindBuildings();renderAll()};bindBuildings()}
function bindBuildings(){let b=$('buildingSelect'), area=currentArea();b.innerHTML=area.buildings.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');b.onchange=()=>{bindFloors();renderAll()};bindFloors()}
function bindFloors(){let f=$('floorSelect'), b=currentBuilding();f.innerHTML=b.floors.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');f.onchange=renderAll}
function renderAll(){let f=currentFloor(), b=currentBuilding(), a=currentArea();$('currentPath').textContent=`${a.name} / ${b.name} / ${f.name}`;$('floorHeight').value=f.height;$('floorLength').value=f.length;$('floorWidth').value=f.width;renderFloor();renderBuilding3d();renderAssets();renderSettings();$('bName').value=b.name;$('bX').value=b.x;$('bY').value=b.y;$('bRot').value=b.rot}
function setView(v){view=v;renderFloor()}
function renderFloor(){let c=$('floorCanvas'), f=currentFloor();c.className='floor-canvas '+(view==='iso'?'iso':'');$('viewName').textContent=view==='top'?'俯视图':view==='iso'?'45°三维斜视图':'楼层编辑模式';$('editPanel').style.display=view==='edit'?'block':'none';['btn-top','btn-45','btn-edit'].forEach(id=>$(id).style.background='#2563eb');let plane=document.createElement('div');plane.className='floor-plane';plane.style.width=Math.max(360,f.length*14)+'px';plane.style.height=Math.max(240,f.width*14)+'px';if(f.planImage)plane.innerHTML+=`<img class="plan-img" src="${f.planImage}">`;f.walls.forEach(w=>plane.appendChild(wallEl(w)));f.assets.forEach(a=>plane.appendChild(assetEl(a)));plane.onclick=e=>canvasClick(e,plane);c.innerHTML='';c.appendChild(plane)}
function wallEl(w){let d=document.createElement('div');d.className='wall';let dx=w.x2-w.x1,dy=w.y2-w.y1,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;Object.assign(d.style,{left:w.x1+'px',top:w.y1+'px',width:len+'px',transform:`rotate(${ang}deg)`});return d}
function assetEl(a){let wrap=document.createElement('div');wrap.className='asset-dot '+(a.type==='配电箱'?'box':'');wrap.style.left=a.x+'px';wrap.style.top=a.y+'px';wrap.onclick=e=>{e.stopPropagation();openAsset(a.id)};let lab=document.createElement('div');lab.className='asset-label';lab.textContent=a.name;wrap.appendChild(lab);return wrap}
function canvasClick(e,plane){let r=plane.getBoundingClientRect(), x=e.clientX-r.left,y=e.clientY-r.top;if(view==='edit'&&drawWall){if(!wallStart){wallStart={x,y};alert('已选择起点，请点击终点')}else{currentFloor().walls.push({x1:wallStart.x,y1:wallStart.y,x2:x,y2:y});wallStart=null;renderFloor()}}}
function toggleDrawWall(){drawWall=!drawWall;$('drawWallBtn').textContent=drawWall?'停止绘制墙体':'开始绘制墙体'}
function autoGenerateWalls(){let f=currentFloor();let w=Math.max(360,f.length*14),h=Math.max(240,f.width*14);f.walls=[{x1:40,y1:40,x2:w-40,y2:40},{x1:w-40,y1:40,x2:w-40,y2:h-40},{x1:w-40,y1:h-40,x2:40,y2:h-40},{x1:40,y1:h-40,x2:40,y2:40},{x1:w*.45,y1:40,x2:w*.45,y2:h-40},{x1:40,y1:h*.55,x2:w-40,y2:h*.55}];renderFloor()}
function clearWalls(){currentFloor().walls=[];renderFloor()}
function applyFloorSettings(){let f=currentFloor();f.height=+$('floorHeight').value;f.length=+$('floorLength').value;f.width=+$('floorWidth').value;renderAll();saveData()}
function uploadPlan(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{currentFloor().planImage=r.result;renderFloor()};r.readAsDataURL(file)}
function addArea(){let name=prompt('区域名称');if(name){state.areas.push({id:'a'+Date.now(),name,buildings:[]});bindSelectors();renderAll()}}
function addBuilding(){let name=prompt('楼栋名称');if(name){currentArea().buildings.push({id:'b'+Date.now(),name,x:0,y:0,rot:0,floors:[]});bindBuildings();renderAll()}}
function addFloor(){let name=prompt('楼层名称，如 3F');if(name){currentBuilding().floors.push({id:'f'+Date.now(),name,height:3.6,length:40,width:25,planImage:'',walls:[],assets:[]});bindFloors();renderAll()}}
function addAsset(type){let f=currentFloor();let id='e'+Date.now();f.assets.push({id,type,name:type+'-'+(f.assets.length+1),x:120+f.assets.length*45,y:120,info:type==='配电箱'?{outgoing:[]}:{}});renderFloor();openAsset(id)}
function openAsset(id){selectedAssetId=id;let a=currentFloor().assets.find(x=>x.id===id);$('modalTitle').textContent=a.type+' 信息填写';$('modalBody').innerHTML=a.type==='配电箱'?boxForm(a):genericForm(a);$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function boxForm(a){let i=a.info||{};let rows=i.outgoing||[];return `<div class="form-grid"><div class="form-section">基本信息</div>${inp('name','配电箱名称',a.name)}${inp('code','配电箱编号',i.code)}${inp('area','所属区域',i.area)}${inp('building','楼栋',i.building)}${inp('floor','楼层',i.floor)}${inp('location','安装位置',i.location)}${inp('responsible','负责人',i.responsible)}${inp('installDate','安装日期',i.installDate,'date')}<div class="form-section">进线信息</div>${inp('incomingCable','进线电缆规格',i.incomingCable)}${inp('incomingLength','进线电缆长度(m)',i.incomingLength)}${inp('incomingSource','上级配电箱',i.incomingSource)}${inp('incomingSwitch','上级出线开关',i.incomingSwitch)}${inp('voltage','进线电压(V)',i.voltage)}${inp('ratedCurrent','额定电流(A)',i.ratedCurrent)}<div class="form-section">开关信息</div>${inp('mainSwitch','总开关型号',i.mainSwitch)}${inp('mainSwitchCapacity','总开关容量(A)',i.mainSwitchCapacity)}${inp('brand','开关品牌',i.brand)}${inp('breakerCount','出线开关数量',i.breakerCount)}<div class="form-section">出线开关 / 回路</div><table class="route-table"><tr><th>回路编号</th><th>开关型号</th><th>电流(A)</th><th>负载名称</th></tr>${[0,1,2,3,4,5,6,7].map(n=>`<tr><td><input id="r${n}c0" value="${rows[n]?.[0]||''}"></td><td><input id="r${n}c1" value="${rows[n]?.[1]||''}"></td><td><input id="r${n}c2" value="${rows[n]?.[2]||''}"></td><td><input id="r${n}c3" value="${rows[n]?.[3]||''}"></td></tr>`).join('')}</table><div class="form-section">备注</div><textarea id="remark">${i.remark||''}</textarea></div>`}
function genericForm(a){let fields=state.categories[a.type]||[];let html=`<div class="form-grid"><div class="form-section">设备信息</div>${inp('name','设备名称',a.name)}${inp('type','设备类别',a.type)}`;fields.forEach(f=>html+=inp('field_'+f,f,a.info?.[f]));html+=`<div class="form-section">保养信息</div>${inp('maintContent','保养内容',a.info?.保养内容)}${inp('maintTime','保养时间/周期',a.info?.保养时间||a.info?.保养周期)}${inp('nextMaint','下次保养日期',a.info?.下次保养,'date')}</div>`;return html}
function inp(id,label,val='',type='text'){return `<label>${label}<input id="${id}" type="${type}" value="${val||''}"></label>`}
function saveAssetModal(){let a=currentFloor().assets.find(x=>x.id===selectedAssetId);if(a.type==='配电箱'){a.name=$('name').value;let ids=['code','area','building','floor','location','responsible','installDate','incomingCable','incomingLength','incomingSource','incomingSwitch','voltage','ratedCurrent','mainSwitch','mainSwitchCapacity','brand','breakerCount','remark'];a.info={};ids.forEach(id=>a.info[id]=$(id)?.value||'');a.info.outgoing=[];for(let n=0;n<8;n++){let row=[0,1,2,3].map(c=>$(`r${n}c${c}`).value);if(row.some(Boolean))a.info.outgoing.push(row)}}else{a.name=$('name').value;let old=a.type;a.type=$('type').value||old;if(!state.categories[a.type])state.categories[a.type]=[];a.info={};(state.categories[a.type]||[]).forEach(f=>a.info[f]=$('field_'+f)?.value||'');a.info.保养内容=$('maintContent').value;a.info.保养时间=$('maintTime').value;a.info.下次保养=$('nextMaint').value}closeModal();renderAll();saveData()}
function switchModule(m){document.querySelectorAll('.module').forEach(x=>x.classList.add('hidden'));$('module-'+m).classList.remove('hidden');$('pageTitle').textContent={map:'楼层视图',building:'楼栋三维',assets:'设备管理',settings:'类别字段',data:'数据导入导出'}[m];document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));event?.target?.classList.add('active');renderAll()}
function renderBuilding3d(){let b=currentBuilding(), floors=b.floors, len=Math.max(...floors.map(f=>f.length),30), wid=Math.max(...floors.map(f=>f.width),20), height=floors.reduce((s,f)=>s+(+f.height||3.6),0);let el=$('building3d');el.innerHTML=`<div class="tower" style="width:${len*7}px;height:${wid*7}px;left:${240+(+b.x||0)}px;top:${150+(+b.y||0)}px;transform:rotateX(58deg) rotateZ(${(-35+(+b.rot||0))}deg)">${floors.map((f,i)=>`<div class="floor-line" style="top:${(i+1)*100/floors.length}%"></div>`).join('')}</div><div style="position:absolute;left:20px;bottom:20px;background:white;padding:12px;border-radius:10px">${b.name}<br>长 ${len}m / 宽 ${wid}m / 高 ${height.toFixed(1)}m<br>位置 X:${b.x} Y:${b.y} 旋转:${b.rot}°</div>`}
function saveBuildingEdit(){let b=currentBuilding();b.name=$('bName').value;b.x=+$('bX').value;b.y=+$('bY').value;b.rot=+$('bRot').value;bindBuildings();renderAll();saveData()}
function renderAssets(){let rows=[];state.areas.forEach(a=>a.buildings.forEach(b=>b.floors.forEach(f=>f.assets.forEach(e=>rows.push(`<tr><td>${a.name}</td><td>${b.name}</td><td>${f.name}</td><td>${e.type}</td><td>${e.name}</td><td><button onclick="selectAndOpen('${a.id}','${b.id}','${f.id}','${e.id}')">编辑</button></td></tr>`)))));$('assetTable').innerHTML='<tr><th>区域</th><th>楼栋</th><th>楼层</th><th>类别</th><th>名称</th><th>操作</th></tr>'+rows.join('')}
function selectAndOpen(a,b,f,e){$('areaSelect').value=a;bindBuildings();$('buildingSelect').value=b;bindFloors();$('floorSelect').value=f;renderAll();openAsset(e)}
function renderSettings(){let list=$('categoryList');list.innerHTML=Object.keys(state.categories).map(c=>`<div class="category-item ${c===selectedCategory?'active':''}" onclick="selectedCategory='${c}';renderSettings()">${c}</div>`).join('');$('fieldList').innerHTML=(state.categories[selectedCategory]||[]).map((f,i)=>`<div class="row"><input value="${f}" onchange="state.categories[selectedCategory][${i}]=this.value"><button onclick="state.categories[selectedCategory].splice(${i},1);renderSettings()">删除</button></div>`).join('')}
function addCategory(){let c=prompt('新类别名称');if(c){state.categories[c]=['型号','品牌','保养内容','保养时间'];selectedCategory=c;renderSettings();saveData()}}
function addField(){let f=prompt('字段名称');if(f){state.categories[selectedCategory].push(f);renderSettings();saveData()}}
function exportJson(){let s=JSON.stringify(state,null,2);$('jsonBox').value=s;let blob=new Blob([s],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='facility-data.json';a.click()}
function importJson(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);saveData();bindSelectors();renderAll()};r.readAsText(file)}
window.onload=()=>{if(localStorage.getItem(key)){state=JSON.parse(localStorage.getItem(key))}}
