const seed=[
{id:'B-001',name:'1栋',type:'楼栋',location:'民企区域 / 1栋',status:'待接入',owner:'厂务部',note:'楼层资料待接入，支持后续导入平面图'},
{id:'B-005',name:'5栋',type:'楼栋',location:'民企区域 / 5栋',status:'正常',owner:'厂务部',note:'已接入 1F/2F，可登记电箱、电缆和设施'},
{id:'B-006',name:'6栋',type:'楼栋',location:'民企区域 / 6栋',status:'待接入',owner:'厂务部',note:'楼层资料待接入'},
{id:'DB-501',name:'5栋1F动力配电箱',type:'电箱',location:'民企区域 / 5栋 / 1F',status:'正常',owner:'张工',note:'上级：总配电房；下级：空压机、照明回路；巡检：温度、异味、积尘、标识'},
{id:'CB-501-A',name:'5栋1F主电缆',type:'电缆',location:'5栋桥架 A 段',status:'正常',owner:'李工',note:'YJV-4x95+1x50，路径：总配电房 → 5栋1F'},
{id:'WO-006',name:'6栋临时电箱',type:'电箱',location:'民企区域 / 6栋 / 1F',status:'异常',owner:'王工',note:'需补充回路标识并检查漏保'}];
let assets=JSON.parse(localStorage.getItem('facilityAssets')||'null')||seed;let selected=null,currentRegion='民企区域';
const $=id=>document.getElementById(id);function save(){localStorage.setItem('facilityAssets',JSON.stringify(assets));render()}function show(a){selected=a;$('detail').innerHTML=`<div class="detail-card"><h2>${a.name}</h2><p>${a.id} · ${a.type}</p><p><b>位置：</b>${a.location}</p><p><b>状态：</b><span class="badge ${a.status==='异常'?'danger':''}">${a.status}</span></p><p><b>负责人：</b>${a.owner}</p><p><b>说明：</b>${a.note||'无'}</p><p><b>二维码链接：</b><br><code>/asset/${a.id}</code></p><button onclick="createInspection('${a.id}')">生成点检记录</button></div>`}
function render(){let q=$('search').value.trim();let list=assets.filter(a=>(!q||JSON.stringify(a).includes(q)));$('assetCount').textContent=assets.length;$('abnormalCount').textContent=assets.filter(a=>a.status==='异常').length;$('taskCount').textContent=assets.filter(a=>a.type==='电箱'||a.type==='电缆').length;$('assetTable').innerHTML=list.map(a=>`<tr><td>${a.id}</td><td>${a.name}</td><td>${a.type}</td><td>${a.location}</td><td><span class="badge ${a.status==='异常'?'danger':''}">${a.status}</span></td><td>${a.owner}</td><td><button onclick='show(${JSON.stringify(a)})'>查看</button></td></tr>`).join('');draw2d()}
function createInspection(id){let a=assets.find(x=>x.id===id);a.note+='\n'+new Date().toLocaleString()+' 已完成一次点检：外观/温度/标识正常。';save();show(a)}
$('search').oninput=render;$('addBtn').onclick=()=>$('modal').classList.remove('hidden');$('cancelBtn').onclick=()=>$('modal').classList.add('hidden');$('saveBtn').onclick=()=>{assets.push({id:'AS-'+Date.now().toString().slice(-6),name:$('mName').value||'未命名资产',type:$('mType').value,location:$('mLocation').value||currentRegion,status:'正常',owner:$('mOwner').value||'未指定',note:$('mNote').value});$('modal').classList.add('hidden');save()};$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(assets,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='facility-assets.json';a.click()};
$('view3d').onclick=()=>{document.querySelector('#threeCanvas').style.display='block';$('floorMap').style.display='none';$('mapTitle').textContent='三维厂区图';$('view3d').classList.add('active');$('view2d').classList.remove('active')};$('view2d').onclick=()=>{document.querySelector('#threeCanvas').style.display='none';$('floorMap').style.display='block';$('mapTitle').textContent='平面图';$('view2d').classList.add('active');$('view3d').classList.remove('active')};
document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{$('title').textContent=b.dataset.region+'总览'});document.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>show(assets.find(a=>a.name===b.dataset.building)||assets[0]));
function draw2d(){let svg=$('floorMap');svg.innerHTML='<rect x="55" y="55" width="790" height="390" fill="#f4f9fb" stroke="#c8dce5"/><path d="M100 350 L420 200 L790 350" fill="none" stroke="#b6d7df"/><text x="80" y="100" class="label">民企区域平面图</text>';[['1栋',220,170],['5栋',500,145],['6栋',660,290]].forEach(([n,x,y])=>{svg.innerHTML+=`<rect class="point" data-name="${n}" x="${x}" y="${y}" width="110" height="150" fill="#dce9ef" stroke="#8fcddd"/><text x="${x+32}" y="${y+78}" class="label">${n}</text>`});assets.filter(a=>a.type==='电箱'||a.type==='电缆').forEach((a,i)=>{let x=470+i*55,y=355-i*28;svg.innerHTML+=`<circle class="point" data-id="${a.id}" cx="${x}" cy="${y}" r="10" fill="${a.status==='异常'?'#e66':'#68b99d'}"/><text x="${x+14}" y="${y+6}" font-size="14">${a.name}</text>`});svg.querySelectorAll('.point').forEach(p=>p.onclick=()=>show(assets.find(a=>a.id===p.dataset.id||a.name===p.dataset.name)))}
function init3d(){const canvas=$('threeCanvas'),scene=new THREE.Scene();scene.background=new THREE.Color(0xf8fcfd);const camera=new THREE.PerspectiveCamera(50,canvas.clientWidth/canvas.clientHeight,.1,1000);camera.position.set(7,7,8);const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setSize(canvas.clientWidth,canvas.clientHeight);const controls=new THREE.OrbitControls(camera,renderer.domElement);scene.add(new THREE.AmbientLight(0xffffff,.8));let light=new THREE.DirectionalLight(0xffffff,.7);light.position.set(5,8,6);scene.add(light);let floor=new THREE.Mesh(new THREE.BoxGeometry(12,.12,7),new THREE.MeshStandardMaterial({color:0eef5f8}));floor.position.y=-.08;scene.add(floor);const defs=[['1栋',-3,1,1.7,3.2],['5栋',1.5,1,1.7,4.4],['6栋',4,-1.2,1.7,3.6]];let clickable=[];defs.forEach(d=>{let m=new THREE.Mesh(new THREE.BoxGeometry(1.4,d[4],1.4),new THREE.MeshStandardMaterial({color:0xcfdde5}));m.position.set(d[1],d[4]/2,d[2]);m.userData.name=d[0];scene.add(m);clickable.push(m)});const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();canvas.onclick=e=>{let r=canvas.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(mouse,camera);let hit=ray.intersectObjects(clickable)[0];if(hit)show(assets.find(a=>a.name===hit.object.userData.name))};function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop()}init3d();render();
